### ISSUE TITLE
Should split MvcFlash into MvcFlash and MvcFlash.Core

### ISSUE THREAD

**Issue by dotnetchris** [khalidabuhakmeh/MvcFlash#4]
If you have a infrastructure project that contains code such as ActionFilterAttributes and want to use MvcFlash for messaging, when you install the package you will get a Content\flash\ folder with associated  styles and pngs.

It would make sense for there to be a core package to be installed outside of the mvc web projects.

**Comment by khalidabuhakmeh** [comment]
thought about this, but then realized that the other package would just be a stylesheet and some images. I don't really want to do that if there is no other value. So I have no plans to split into two packages.
