### ISSUE TITLE
How do I tell whether there are any flash messages in the @Html.flash

### ISSUE THREAD

**Issue by gmhawash** [khalidabuhakmeh/MvcFlash#5]
I want to be able to wrap the flash messages into one wrapper, but I want to show/hide that wrapper depending on whether there are any flash messages in the flash object.

I tried to use Flash.Count, but it fails with 'invalid object'

Is there a way to do so?

If Flash.Count then
 <div id="error">
   @Html.Flash
</div>

**Comment by khalidabuhakmeh** [comment]
You do that within the FlashTemplate file, you have access to the type of each message so you'll be able to wrap it accordingly. Check out the sample project to see what I mean.
