### ISSUE TITLE
ASP.NET MVC4 Compatibility 

### ISSUE THREAD

**Issue by TechplexEngineer** [khalidabuhakmeh/MvcFlash#8]
So I'm upgrading one of my asp.net mvc3 apps that uses this awesome package, I think all that is needed is a modification to the web.config. I have created a branch on my fork with the web.config.transform updated.

See here: https://github.com/TechplexEngineer/MvcFlash/tree/mvc4

**Comment by khalidabuhakmeh** [comment]
hmmm.... strange. I am able to install this directly into an ASP.NET MVC 4 project. I am not sure about the upgrade path though. I think most devs who are upgrading should figure this out on their own and I'd rather not mess with the web.config if I don't have to. Thanks, glad you think this package is awesome.
