### ISSUE TITLE
html markup in flash message

### ISSUE THREAD

**Issue by TechplexEngineer** [khalidabuhakmeh/MvcFlash#9]
I'm trying to do something like this `Flash.Error("error message <a href=\"\">link</a>");` but somewhere the html is getting escaped. 
So the message that is output is `error message <a href="">link</a>`

Is there a way around the escaping?

**Comment by khalidabuhakmeh** [comment]
You could in your Flash message template (cshtml) decode using HttpUtlity.

Kind Regards,

Khalid Abuhakmeh

**Comment by TechplexEngineer** [comment]
Exactly what I needed, thanks!

I changed this: `@Model.Message.Text`

to this: `@Html.Raw(HttpUtility.HtmlDecode(Model.Message.Text))`

**Comment by khalidabuhakmeh** [comment]
Great to hear it helped. I usually try to pass up a model with my flash messages and generate the links in the view, but I can see the value of just doing it in the controller too. MvcFlash2 has a better story around models and passing extra data. Check it out.
